version: 2

node_key: &node_key
  key: node-deps-v2-{{ arch }}-{{ checksum "yarn.lock" }}-{{ checksum "circle.yml" }}

restore_node: &restore_node
  restore_cache:
    <<: *node_key

install_node: &install_node
  run:
    name: node deps
    command: |
      if [ ! -d node_modules ]; then
        yarn --pure-lockfile
      fi

save_node: &save_node
  save_cache:
    <<: *node_key
    paths:
      - node_modules

container_defaults: &defaults
  docker:
    - image: circleci/node:10-browsers
      environment:
        JOBS: 2

jobs:
  install:
    <<: *defaults
    steps:
      - checkout

      - <<: *restore_node
      - <<: *install_node
      - <<: *save_node

  test:
    <<: *defaults
    environment:
      CIRCLE_TEST_REPORTS: test-results

    steps:
      - checkout
      - <<: *restore_node

      - run:
          name: Addon Tests
          command: npx ember test

      - store_test_results:
          path: test-results/

  build-storybook:
    <<: *defaults
    steps:
      - checkout
      - <<: *restore_node
      - run:
          name: Build Ember
          command: npx ember build
      - run:
          name: Build Docs
          command: npm run build-storybook
      - persist_to_workspace:
          root: .
          paths:
            - storybook-static

  deploy-storybook:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Disable jekyll builds
          command: touch storybook-static/.nojekyll
      - run:
          name: Configure git user
          command: |
            git config user.email "ci-build@nypublicradio.org"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "ab:f0:e6:36:b3:6d:67:77:fe:fc:b3:22:23:59:a2:c6"
      - run:
          name: Deploy docs to gh-pages branch
          command: npx gh-pages --dotfiles --message "[skip ci] Publish Docs" --dist storybook-static

workflows:
  version: 2
  just-test:
    jobs:
      - install:
          filters:
            branches:
              ignore: master
      - test:
          requires:
            - install

  deploy-storybook:
    jobs:
      - install:
          filters:
            branches:
              only: master
      - test:
          requires:
            - install
      - build-storybook:
          requires:
            - test
      - deploy-storybook:
          requires:
            - build-storybook
